# Generated by Django 3.0.4 on 2020-03-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otoapp.Student'),
        ),
    ]
