# Generated by Django 3.0.4 on 2020-03-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otoapp', '0002_auto_20200317_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=models.SET(6), to='otoapp.Student'),
        ),
    ]
